GET http://localhost:5000/tes1

####
POST http://localhost:5000/445566/token
Content-Type: application/json

{
    "requireauth": true,
    "password": "445566",
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiMTEyMjMzIiwiaWF0IjoxNjYzNzA4OTk4LCJleHAiOjE2NjM3MTI1OTh9.QT12dB4-Old9XlJ927oOFhcuL-iK7KSbVQRxdOgQTsM"
}

### 2
POST http://localhost:5000/445566
Content-Type: application/json

{
    "requireauth": false,
    "password": "",
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiNDQ1NTY2IiwiaWF0IjoxNjY0MDA3MzM2LCJleHAiOjE2NjQwMTA5MzZ9.AqfIhX-PBn7ie9J3EmjX35VXKeCRr2CcK4ufUXm39ks"
}


### 3
DELETE http://localhost:5000/wwww1/todo/33
Content-Type: application/json

{
    "text": "heel",
    "completed": true
}

